### PR TITLE
[Feat]: Adding online medicine feature and set up the payment integeration

### LINKED ISSUE #2: [Feat]: Adding online medicine feature and set up the payment integeration
Description:
Introducing an online medicine ordering feature in Medihub to provide enhanced convenience for patients and healthcare providers. This feature will empower patients to seamlessly browse and order prescribed medications directly from the Medihub platform, streamlining the medication procurement process and elevating the overall user experience.

Benefits:

Convenient access to prescribed medications from the comfort of home, improving patient satisfaction and adherence to treatment plans.
Simplified ordering process for both patients and healthcare providers, reducing administrative burdens and enhancing operational efficiency.
Seamless integration with existing Medihub functionalities, ensuring a cohesive and comprehensive healthcare management platform.

Please assign it to me. I will work on it.

### PR DESCRIPTION
**Pull request by tuwid-Ashish**
## Description

This pull request introduces new backend controllers, models, and routes to establish API endpoints essential for the functionality of an e-commerce medicine selling system. On the frontend, it adds new pages and components to interact with medicine products, including browsing categories, viewing single products, and adding products to the cart.

## Related Issues

- Fixes #2 (The issue is now fully resolved)

## Changes

- Added `PaymentController`, `ProductController`, and `CartController` to the backend.
- Created new models for user payments and product management.
- Established routes for product listing, Rezerpay integration, and shopping cart management.
- Developed frontend pages for product categories, product details, and the shopping cart.
- Implemented add-to-cart functionality with database storage .

## How

- Utilized MVC architecture to separate concerns in the backend.
- Employed RESTful principles for API design.
- Leveraged React.js for dynamic frontend development.
- Utilize best practice to create clean Api management on frontend.

## Testing

- Conducted unit tests for all new backend controllers and models.
- Performed integration testing for API endpoints.
- Executed manual testing of frontend components .

## Screenshots

Before changes:
!Before
image

After changes:
!After

https://github.com/itsmohit097/medi-hub/assets/125805624/1b0752c2-2dfc-4c4e-9ef9-a69392314be4

## Additional Notes

- The frontend design is minimalistic and focuses on functionality.
- Further UI enhancements is required to increase user experience and responsiveness.
- The add to cart page is not opening due to user Authentication and signup system is not added but its the are functional require Userid.
- Products adding deletion and update are only for admin and not frontend included for this.
- I worked only in main because I have both frontend and backend side work

## Checklist
Replace "[ ]" with "[x]" to mark them as completed.
- [x] I have forked the repo and pushed the changes according to contribution guidelines.
- [x] I have tested these changes locally.
- [x] I have tried to maintain the consistency of the code.
- [x] I have tested these changes locally.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by itsmohit097** [comment]
@tuwid-Ashish your files are conflicting with the other files. I already mentioned that do the fork and branch process correctly (read contribution.md).
You have to push your code in the backend branch (already created). 
Your code is affecting the main branch.
Sorry, I can't merge this.. Pls do the correction.

**Review by itsmohit097 — COMMENTED** [review]
Not Approved

**Comment by tuwid-Ashish** [comment]
Hii @itsmohit097 ,

I would shift my whole code to the backend Branch as its affect been on main , I forked the repo with all branches and revert my main branch commit. 
This would sure the conflicts not accrue on integration.

**Comment by itsmohit097** [comment]
@tuwid-Ashish Raise a new PR when you did this

**Comment by tuwid-Ashish** [comment]
Hii @itsmohit097 , 

can you close this PR as  tomorrow after is my final sem exam. that way I am not able to do work on changes at that time .
After that I will raise new PR for that Feature I hope you can understand and corporate with me

**Comment by itsmohit097** [comment]
> Hii @itsmohit097 ,
> 
> can you close this PR as tomorrow after is my final sem exam. that way I am not able to do work on changes at that time . After that I will raise new PR for that Feature I hope you can understand and corporate with me

No prob l said u the process on the discord work in steps

**Pull request closed without merging**
