### PR TITLE
fix(navbar): improve visibility and responsiveness

### LINKED ISSUE #34: [Enhancement Functionality/Styling] : Making navbar responsive (hamburger menu) and fix the bug hover effect on login
All the navbar links are getting disappeared when i open in smaller size.

Screenshots:
image
image

I will fix this.

Please assign me this issue under GSSOC'24.

### PR DESCRIPTION
**Pull request by MitulSonagara**
## Description

I have added a hamburger menu. Also fixed the hover effect on login, and made it properly visible.

## Related Issues*

- Fixes #34 

## Screenshots! (Optional)

Before changes:
(screenshot)

After changes:
(screenshot)

## Checklist
Replace "[ ]" with "[x]" to mark them as completed.
- [x] I have forked the repo and pushed the changes according to contribution guidelines.
- [x] I have tested these changes locally.
- [x] I have tried to maintain the consistency of the code.
- [x] I have tested these changes locally.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by itsmohit097** [comment]
Contribution guidelines were not followed properly

**Comment by MitulSonagara** [comment]
@itsmohit097 can you tell me what I missed?

**Comment by itsmohit097** [comment]
@MitulSonagara, the fork and branch processes have not been done correctly. Please take a look at the contribution.md file.

**Comment by itsmohit097** [comment]
@MitulSonagara raise a new PR

**Comment by MitulSonagara** [comment]
@itsmohit097 Raise a same PR or I need to change something??

**Pull request closed without merging**
